Drag and drop Full page element
Hermit-Tools/Thumbnail-Maker pull request #36
Opened 2020-10-16 12:56 UTC by nsandor-webDev

Created dragndrop.js file which **allow to upload a file by dragging it from your computer**. Drop zone is full page overlay.

2020-10-17 08:14 UTC, mmaismma commented
At Hermit-Tools, one of our agendas is not to use any external framework. It was already mentioned in the wiki, but somehow not in the contributing guidelines (it has been fixed).  
Your code uses the *jQuery* framework. But luckily, the amount of jQuery used in your code is very minimal and we can easily change those lines to plain JavaScript. I will comment on every line in jQuery about a possible alternative in plain JavaScript.

Other than that, your coding is perfect. It is simple, readable, and works with excellence. Once the Javascript is flattened, I'll accept the PR as soon as possible.

2020-10-17 08:57 UTC, mmaismma requested changes
Changes are mentioned in comments, reply your feedback on individual comments. Once we find the best code, I'll accept the PR.

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +(function($) {
Can replace with
```js
function () {
```

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        dropInput = body.find('#bgInput'),  // input file element from right part
Can replace with
```js
var dropZone = document.getElementById('dropzone'), // Full page overlay drop zone element
    dropInput = document.getElementById('dropzone'), // Input file element from right part
```
Removed the `body` variable.

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +            }
This piece of code is very faulty. It should be replaced with 
```js
if (dt.items[i].kind === 'file') { // Dragged item is a file
    if (dt.items[i].type.indexOf('image') === 0) { // Drageed file is an image
        return true;
    }
}
```
This code does better checking. The previous code does not work,

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        return false;
This should be removed.

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        dropInput.addClass('dropInput');
This piece of code is in jQuery, it should be replaced with
```js
dropZone.style.visibilty = "visible";
dropZone.style.opacity = 1;
dropZone.style.fontSize = "3rem";

dropInput.classList.add('dropInput')
```

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        dropInput.removeClass('dropInput');
Code is in jQuery, should be replaced with
```js
dropZone.style.visibilty = "";
dropZone.style.opacity = "";
dropZone.style.fontSize = "";

dropInput.classList.remove('dropInput')
```
Blank values will eventually become the default value that is specified in the CSS file.

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +// When you will be using some JS framework with "$" symbol, this part of CODE will be always in jQuery
Since jQuery will not be used, these lines should be replaced with
```js
}
```

2020-10-17 08:57 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        };
These variables should be removed as they will not be later used, values are specified as local strings.

2020-10-17 12:46 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +(function($) {
Github's glitch: I only meant to comment on line 9.

2020-10-17 12:46 UTC, mmaismma commented on Source/cubfan135/dragndrop.js
> +        return false;
Github's glitch again: I only meant to comment on line 67.

2020-10-19 10:04 UTC, nsandor-webDev commented
jQuery -> pure javascript - done. Sorry I don't know how to update pull request. I pushed commit and it's showed nder your activity (added milestone). I'm new in github :)
@mmaismma
#29
Fixes #29

2020-10-19 10:12 UTC, nsandor-webDev commented
And - Thank you for your help (writing complete javascript code lines). Some lines were with mistakes but don't worry I fixed them ;) Everything is now in pure JavaScript !

2020-10-21 03:46 UTC, mmaismma commented
There are numerous problems in your code that make it not working. I will state all the problems in a review. Fix all the problems and then make a new pull request.

2020-10-21 04:57 UTC, nsandor-webDev commented
> There are numerous problems in your code that make it not working. I will state all the problems in a review. Fix all the problems and then make a new pull request.

What browser you are testing with ? Nevest version of Chrome works good.

2020-10-22 07:26 UTC, mmaismma commented
I am using the latest version of Microsoft Edge (Chromium) i.e. basically Chrome talking of functionality.

First of all, let us clean the code.

2020-10-22 07:28 UTC, mmaismma commented
I am using the latest version of Microsoft Edge (Chromium) i.e. basically Chrome talking of functionality.

2020-10-22 10:26 UTC, mmaismma requested changes
**I made local copies of all the files in this PR and the feature works completely fine, there must be a bug with Chrome DevTools.**

Your core idea is to make `bgInput` span all the window when something is dragged on the window. On dropping the file, the browser *automatically* uploads the file to the input. Meanwhile, on drag, you show the *Drag File Here* `div` to make the process interactive.  
This idea lacks support for IE, but we are not supporting it anyway. Since the browser is doing all the stuff itself, no *Drag and Drop API logic* is required. This is a very clever solution to the issue. But there are a few things I would suggest.

1. Stop calling `preventDef(e)`. This function contains only two lines of code; calling the function instead of directly writing those two lines makes confusion.
2. `lastTarget` is defined as a global variable, would be better if you define it with `var`.
3. Changing `font-size` for the animation will cause a minor issue. When the width of the window is small, the text will add new lines as shown in the pictures below. Animating the text with `transform` would be better. Keep the default `font-size` = `3rem`, add `transform: scale(0.75);` in the CSS file. In `showDropZone()` replace line 61 with `dropZoneTitle.style.transform = ""`.
<img src="https://user-images.githubusercontent.com/44745238/96858770-5803a200-147e-11eb-826b-ef12f769cd3b.png" width="240"> <img src="https://user-images.githubusercontent.com/44745238/96858877-736ead00-147e-11eb-858d-af09aeee9e8c.png" width="240">

2020-10-25 16:07 UTC, nsandor-webDev commented
Pushed. I hope now it is all good.

@mmaismma 
#29
Fixes #29

2020-10-26 07:45 UTC, mmaismma approved these changes
The `transform` animation was not working. Since this was a very minor problem, I fixed it myself.

Anyways, your code was very clever and it deserves every right to be merged into `master`. I loved the code discussion too, happy developing✌!

2020-10-26 07:45 UTC, merged